# Generated by Django 6.0.7 on 2026-07-18 18:57

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeocodeCache",
            fields=[
                (
                    "cache_key",
                    models.CharField(max_length=600, primary_key=True, serialize=False),
                ),
                ("provider", models.CharField(max_length=40)),
                ("normalized_query", models.CharField(max_length=500)),
                ("resolved_name", models.CharField(max_length=500)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180")),
                            django.core.validators.MaxValueValidator(Decimal("180")),
                        ],
                    ),
                ),
                ("cached_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["cache_key"],
            },
        ),
        migrations.CreateModel(
            name="RouteCache",
            fields=[
                (
                    "cache_key",
                    models.CharField(max_length=300, primary_key=True, serialize=False),
                ),
                ("provider", models.CharField(max_length=40)),
                ("profile", models.CharField(max_length=40)),
                ("start_latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "start_longitude",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                (
                    "finish_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "finish_longitude",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("geometry", models.JSONField()),
                (
                    "distance_meters",
                    models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)]),
                ),
                (
                    "duration_seconds",
                    models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)]),
                ),
                ("cached_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["cache_key"],
            },
        ),
    ]
