# Generated by Django 6.0.7 on 2026-07-18 18:33

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_truckstop_id", models.PositiveBigIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=2)),
                ("rack_id", models.PositiveIntegerField()),
                (
                    "retail_price",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("1E-8"))],
                    ),
                ),
                (
                    "source_row_count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180")),
                            django.core.validators.MaxValueValidator(Decimal("180")),
                        ],
                    ),
                ),
                (
                    "coordinate_accuracy",
                    models.CharField(
                        choices=[
                            ("city_centroid", "City centroid"),
                            ("unmatched", "Unmatched"),
                        ],
                        default="unmatched",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["opis_truckstop_id"],
                "indexes": [models.Index(fields=["state", "city"], name="fuel_state_city_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("latitude__isnull", True), ("longitude__isnull", True)),
                            models.Q(
                                ("latitude__isnull", False),
                                ("longitude__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="fuel_coordinates_both_or_neither",
                    )
                ],
            },
        ),
    ]
